

CREATE TABLE `countries` (
  `id` int(11) NOT NULL,
  `iso_code` varchar(2) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `en_label` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `it_label` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `de_label` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `fr_label` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `es_label` varchar(15) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `pt_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ro_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `el_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `jp_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `br_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `fi_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `ru_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `zh_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `pl_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `hu_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `he_label` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `countries` (`id`, `iso_code`, `en_label`, `it_label`, `de_label`, `fr_label`, `es_label`, `pt_label`, `ro_label`, `el_label`, `jp_label`, `br_label`, `fi_label`, `ru_label`, `zh_label`, `pl_label`, `hu_label`, `he_label`) VALUES
(1, 'AF', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Afganistán', 'Afeganistão', 'Afganistan', 'Αφγανιστάν', 'アフガニスタン', 'Afghanistan', 'Afganistan', 'Афганистан', '阿富汗', 'Afganistan', 'Afganisztán', 'אפגניסטן'),
(2, 'AX', 'Islands', 'Isole ', 'Ålandinseln', 'Îles Åland', 'Islas Åland', 'Ilhas Åland', 'Insulele Åland', 'Νήσοι Όλαντ', 'オーランド諸島', 'Inizi Åland', 'Ahvenanmaa', 'Аландские о-ва', '奥兰群岛', 'Wyspy Alandzkie', 'Åland-szigetek', 'איי אולנד'),
(3, 'AL', 'Albania', 'Albania', 'Albanien', 'Albanie', 'Albania', 'Albânia', 'Albania', 'Αλβανία', 'アルバニア', 'Albania', 'Albania', 'Албания', '阿尔巴尼亚', 'Albania', 'Albánia', 'אלבניה'),
(4, 'DZ', 'Algeria', 'Algeria', 'Algerien', 'Algérie', 'Argelia', 'Argélia', 'Algeria', 'Αλγερία', 'アルジェリア', 'Aljeria', 'Algeria', 'Алжир', '阿尔及利亚', 'Algieria', 'Algéria', 'אלג׳יריה'),
(5, 'AS', 'American Samoa', 'Samoa americane', 'Amerikanisch-Sa', 'Samoa américain', 'Samoa Americana', 'Samoa Americana', 'Samoa Americană', 'Αμερικανική Σαμόα', '米領サモア', 'Samoa Amerikan', 'Amerikan Samoa', 'Американское Самоа', '美属萨摩亚', 'Samoa Amerykańskie', 'Amerikai Szamoa', 'סמואה האמריקנית'),
(6, 'AD', 'Andorra', 'Andorra', 'Andorra', 'Andorre', 'Andorra', 'Andorra', 'Andorra', 'Ανδόρα', 'アンドラ', 'Andorra', 'Andorra', 'Андорра', '安道尔', 'Andora', 'Andorra', 'אנדורה'),
(7, 'AO', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Angola', 'Ανγκόλα', 'アンゴラ', 'Angola', 'Angola', 'Ангола', '安哥拉', 'Angola', 'Angola', 'אנגולה'),
(8, 'AI', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguilla', 'Anguila', 'Anguilla', 'Anguilla', 'Ανγκουίλα', 'アンギラ', 'Anguilla', 'Anguilla', 'Ангилья', '安圭拉', 'Anguilla', 'Anguilla', 'אנגילה'),
(9, 'AQ', 'Antarctica', 'Antartide', 'Antarktis', 'Antarctique', 'Antártida', 'Antártida', 'Antarctica', 'Ανταρκτική', '南極', 'Antarktika', 'Antarktis', 'Антарктида', '南极洲', 'Antarktyka', 'Antarktisz', 'אנטארקטיקה'),
(10, 'AG', 'Antigua & Barbu', 'Antigua e Barbu', 'Antigua und Bar', 'Antigua-et-Barb', 'Antigua y Barbu', 'Antígua e Barbuda', 'Antigua și Barbuda', 'Αντίγκουα και Μπαρμπ', 'アンティグア・バーブーダ', 'Antigua ha Barbuda', 'Antigua ja Barbuda', 'Антигуа и Барбуда', '安提瓜和巴布达', 'Antigua i Barbuda', 'Antigua és Barbuda', 'אנטיגואה וברבודה'),
(11, 'AR', 'Argentina', 'Argentina', 'Argentinien', 'Argentine', 'Argentina', 'Argentina', 'Argentina', 'Αργεντινή', 'アルゼンチン', 'Arcʼhantina', 'Argentiina', 'Аргентина', '阿根廷', 'Argentyna', 'Argentína', 'ארגנטינה'),
(12, 'AM', 'Armenia', 'Armenia', 'Armenien', 'Arménie', 'Armenia', 'Armênia', 'Armenia', 'Αρμενία', 'アルメニア', 'Armenia', 'Armenia', 'Армения', '亚美尼亚', 'Armenia', 'Örményország', 'ארמניה'),
(13, 'AW', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Aruba', 'Αρούμπα', 'アルバ', 'Aruba', 'Aruba', 'Аруба', '阿鲁巴', 'Aruba', 'Aruba', 'ארובה'),
(14, 'AC', 'Ascension Islan', 'Isola Ascension', 'Ascension', 'Île de l’Ascens', 'Isla de la Asce', 'Ilha de Ascensão', 'Insula Ascension', 'Νήσος Ασενσιόν', 'アセンション島', 'Enez Ascension', 'Ascension-saari', 'о-в Вознесения', '阿森松岛', 'Wyspa Wniebowstąpien', 'Ascension-sziget', 'האי אסנשן'),
(15, 'AU', 'Australia', 'Australia', 'Australien', 'Australie', 'Australia', 'Austrália', 'Australia', 'Αυστραλία', 'オーストラリア', 'Aostralia', 'Australia', 'Австралия', '澳大利亚', 'Australia', 'Ausztrália', 'אוסטרליה'),
(16, 'AT', 'Austria', 'Austria', 'Österreich', 'Autriche', 'Austria', 'Áustria', 'Austria', 'Αυστρία', 'オーストリア', 'Aostria', 'Itävalta', 'Австрия', '奥地利', 'Austria', 'Ausztria', 'אוסטריה'),
(17, 'AZ', 'Azerbaijan', 'Azerbaigian', 'Aserbaidschan', 'Azerbaïdjan', 'Azerbaiyán', 'Azerbaijão', 'Azerbaidjan', 'Αζερμπαϊτζάν', 'アゼルバイジャン', 'Azerbaidjan', 'Azerbaidžan', 'Азербайджан', '阿塞拜疆', 'Azerbejdżan', 'Azerbajdzsán', 'אזרבייג׳ן'),
(18, 'BS', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Bahamas', 'Μπαχάμες', 'バハマ', 'Bahamas', 'Bahama', 'Багамы', '巴哈马', 'Bahamy', 'Bahama-szigetek', 'איי בהאמה'),
(19, 'BH', 'Bahrain', 'Bahrein', 'Bahrain', 'Bahreïn', 'Baréin', 'Bahrein', 'Bahrain', 'Μπαχρέιν', 'バーレーン', 'Bahrein', 'Bahrain', 'Бахрейн', '巴林', 'Bahrajn', 'Bahrein', 'בחריין'),
(20, 'BD', 'Bangladesh', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'Bangladés', 'Bangladesh', 'Bangladesh', 'Μπανγκλαντές', 'バングラデシュ', 'Bangladesh', 'Bangladesh', 'Бангладеш', '孟加拉国', 'Bangladesz', 'Banglades', 'בנגלדש'),
(21, 'BB', 'Barbados', 'Barbados', 'Barbados', 'Barbade', 'Barbados', 'Barbados', 'Barbados', 'Μπαρμπάντος', 'バルバドス', 'Barbados', 'Barbados', 'Барбадос', '巴巴多斯', 'Barbados', 'Barbados', 'ברבדוס'),
(22, 'BY', 'Belarus', 'Bielorussia', 'Belarus', 'Biélorussie', 'Bielorrusia', 'Bielorrússia', 'Belarus', 'Λευκορωσία', 'ベラルーシ', 'Belarus', 'Valko-Venäjä', 'Беларусь', '白俄罗斯', 'Białoruś', 'Belarusz', 'בלארוס'),
(23, 'BE', 'Belgium', 'Belgio', 'Belgien', 'Belgique', 'Bélgica', 'Bélgica', 'Belgia', 'Βέλγιο', 'ベルギー', 'Belgia', 'Belgia', 'Бельгия', '比利时', 'Belgia', 'Belgium', 'בלגיה'),
(24, 'BZ', 'Belize', 'Belize', 'Belize', 'Belize', 'Belice', 'Belize', 'Belize', 'Μπελίζ', 'ベリーズ', 'Belize', 'Belize', 'Белиз', '伯利兹', 'Belize', 'Belize', 'בליז'),
(25, 'BJ', 'Benin', 'Benin', 'Benin', 'Bénin', 'Benín', 'Benin', 'Benin', 'Μπενίν', 'ベナン', 'Benin', 'Benin', 'Бенин', '贝宁', 'Benin', 'Benin', 'בנין'),
(26, 'BM', 'Bermuda', 'Bermuda', 'Bermuda', 'Bermudes', 'Bermudas', 'Bermudas', 'Bermuda', 'Βερμούδες', 'バミューダ', 'Bermuda', 'Bermuda', 'Бермуды', '百慕大', 'Bermudy', 'Bermuda', 'ברמודה'),
(27, 'BT', 'Bhutan', 'Bhutan', 'Bhutan', 'Bhoutan', 'Bután', 'Butão', 'Bhutan', 'Μπουτάν', 'ブータン', 'Bhoutan', 'Bhutan', 'Бутан', '不丹', 'Bhutan', 'Bhután', 'בהוטן'),
(28, 'BO', 'Bolivia', 'Bolivia', 'Bolivien', 'Bolivie', 'Bolivia', 'Bolívia', 'Bolivia', 'Βολιβία', 'ボリビア', 'Bolivia', 'Bolivia', 'Боливия', '玻利维亚', 'Boliwia', 'Bolívia', 'בוליביה'),
(29, 'BA', 'Bosnia & Herzeg', 'Bosnia ed Erzeg', 'Bosnien und Her', 'Bosnie-Herzégov', 'Bosnia-Herzegov', 'Bósnia e Herzegovina', 'Bosnia și Herțegovin', 'Βοσνία - Ερζεγοβίνη', 'ボスニア・ヘルツェゴビナ', 'Bosnia ha Herzegovin', 'Bosnia ja Hertsegovi', 'Босния и Герцеговина', '波斯尼亚和黑塞哥维那', 'Bośnia i Hercegowina', 'Bosznia-Hercegovina', 'בוסניה והרצגובינה'),
(30, 'BW', 'Botswana', 'Botswana', 'Botsuana', 'Botswana', 'Botsuana', 'Botsuana', 'Botswana', 'Μποτσουάνα', 'ボツワナ', 'Botswana', 'Botswana', 'Ботсвана', '博茨瓦纳', 'Botswana', 'Botswana', 'בוצוואנה'),
(31, 'BR', 'Brazil', 'Brasile', 'Brasilien', 'Brésil', 'Brasil', 'Brasil', 'Brazilia', 'Βραζιλία', 'ブラジル', 'Brazil', 'Brasilia', 'Бразилия', '巴西', 'Brazylia', 'Brazília', 'ברזיל'),
(32, 'IO', 'British Indian ', 'Territorio brit', 'Britisches Terr', 'Territoire brit', 'Territorio Brit', 'Território Britânico', 'Teritoriul Britanic ', 'Βρετανικά Εδάφη Ινδι', '英領インド洋地域', 'Tiriad breizhveurat ', 'Brittiläinen Intian ', 'Британская территори', '英属印度洋领地', 'Brytyjskie Terytoriu', 'Brit Indiai-óceáni T', 'הטריטוריה הבריטית בא'),
(33, 'VG', 'British Virgin ', 'Isole Vergini B', 'Britische Jungf', 'Îles Vierges br', 'Islas Vírgenes ', 'Ilhas Virgens Britân', 'Insulele Virgine Bri', 'Βρετανικές Παρθένοι ', '英領ヴァージン諸島', 'Inizi Gwercʼh Breizh', 'Brittiläiset Neitsyt', 'Виргинские о-ва (Бри', '英属维尔京群岛', 'Brytyjskie Wyspy Dzi', 'Brit Virgin-szigetek', 'איי הבתולה הבריטיים'),
(34, 'BN', 'Brunei', 'Brunei', 'Brunei Darussal', 'Brunéi Darussal', 'Brunéi', 'Brunei', 'Brunei', 'Μπρουνέι', 'ブルネイ', 'Brunei', 'Brunei', 'Бруней-Даруссалам', '文莱', 'Brunei', 'Brunei', 'ברוניי'),
(35, 'BG', 'Bulgaria', 'Bulgaria', 'Bulgarien', 'Bulgarie', 'Bulgaria', 'Bulgária', 'Bulgaria', 'Βουλγαρία', 'ブルガリア', 'Bulgaria', 'Bulgaria', 'Болгария', '保加利亚', 'Bułgaria', 'Bulgária', 'בולגריה'),
(36, 'BF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Burquina Faso', 'Burkina Faso', 'Μπουρκίνα Φάσο', 'ブルキナファソ', 'Burkina Faso', 'Burkina Faso', 'Буркина-Фасо', '布基纳法索', 'Burkina Faso', 'Burkina Faso', 'בורקינה פאסו'),
(37, 'BI', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Burundi', 'Μπουρούντι', 'ブルンジ', 'Burundi', 'Burundi', 'Бурунди', '布隆迪', 'Burundi', 'Burundi', 'בורונדי'),
(38, 'KH', 'Cambodia', 'Cambogia', 'Kambodscha', 'Cambodge', 'Camboya', 'Camboja', 'Cambodgia', 'Καμπότζη', 'カンボジア', 'Kambodja', 'Kambodža', 'Камбоджа', '柬埔寨', 'Kambodża', 'Kambodzsa', 'קמבודיה'),
(39, 'CM', 'Cameroon', 'Camerun', 'Kamerun', 'Cameroun', 'Camerún', 'República dos Camarõ', 'Camerun', 'Καμερούν', 'カメルーン', 'Kameroun', 'Kamerun', 'Камерун', '喀麦隆', 'Kamerun', 'Kamerun', 'קמרון'),
(40, 'CA', 'Canada', 'Canada', 'Kanada', 'Canada', 'Canadá', 'Canadá', 'Canada', 'Καναδάς', 'カナダ', 'Kanada', 'Kanada', 'Канада', '加拿大', 'Kanada', 'Kanada', 'קנדה'),
(41, 'IC', 'Canary Islands', 'Isole Canarie', 'Kanarische Inse', 'Îles Canaries', 'Canarias', 'Ilhas Canárias', 'Insulele Canare', 'Κανάριοι Νήσοι', 'カナリア諸島', 'Inizi Kanariez', 'Kanariansaaret', 'Канарские о-ва', '加纳利群岛', 'Wyspy Kanaryjskie', 'Kanári-szigetek', 'האיים הקנריים'),
(42, 'CV', 'Cape Verde', 'Capo Verde', 'Cabo Verde', 'Cap-Vert', 'Cabo Verde', 'Cabo Verde', 'Capul Verde', 'Πράσινο Ακρωτήριο', 'カーボベルデ', 'Kab-Glas', 'Kap Verde', 'Кабо-Верде', '佛得角', 'Republika Zielonego ', 'Zöld-foki Köztársasá', 'כף ורדה'),
(43, 'BQ', 'Caribbean Nethe', 'Caraibi olandes', 'Bonaire, Sint E', 'Pays-Bas caribé', 'Caribe neerland', 'Países Baixos Caribe', 'Insulele Caraibe Ola', 'Ολλανδία Καραϊβικής', 'オランダ領カリブ', 'Karib Nederlandat', 'Karibian Alankomaat', 'Бонэйр, Синт-Эстатиу', '荷属加勒比区', 'Niderlandy Karaibski', 'Holland Karib-térség', 'האיים הקריביים ההולנ'),
(44, 'KY', 'Cayman Islands', 'Isole Cayman', 'Kaimaninseln', 'Îles Caïmans', 'Islas Caimán', 'Ilhas Cayman', 'Insulele Cayman', 'Νήσοι Κάιμαν', 'ケイマン諸島', 'Inizi Cayman', 'Caymansaaret', 'Каймановы о-ва', '开曼群岛', 'Kajmany', 'Kajmán-szigetek', 'איי קיימן'),
(45, 'CF', 'Central African', 'Repubblica Cent', 'Zentralafrikani', 'République cent', 'República Centr', 'República Centro-Afr', 'Republica Centrafric', 'Κεντροαφρικανική Δημ', '中央アフリカ共和国', 'Republik Kreizafrika', 'Keski-Afrikan tasava', 'ЦАР', '中非共和国', 'Republika Środkowoaf', 'Közép-afrikai Köztár', 'הרפובליקה של מרכז אפ'),
(46, 'EA', 'Ceuta & Melilla', 'Ceuta e Melilla', 'Ceuta und Melil', 'Ceuta et Melill', 'Ceuta y Melilla', 'Ceuta e Melilha', 'Ceuta și Melilla', 'Θεούτα και Μελίλα', 'セウタ・メリリャ', 'Ceuta ha Melilla', 'Ceuta ja Melilla', 'Сеута и Мелилья', '休达及梅利利亚', 'Ceuta i Melilla', 'Ceuta és Melilla', 'סאוטה ומלייה'),
(47, 'TD', 'Chad', 'Ciad', 'Tschad', 'Tchad', 'Chad', 'Chade', 'Ciad', 'Τσαντ', 'チャド', 'Tchad', 'Tšad', 'Чад', '乍得', 'Czad', 'Csád', 'צ׳אד'),
(48, 'CL', 'Chile', 'Cile', 'Chile', 'Chili', 'Chile', 'Chile', 'Chile', 'Χιλή', 'チリ', 'Chile', 'Chile', 'Чили', '智利', 'Chile', 'Chile', 'צ׳ילה'),
(49, 'CN', 'China', 'Cina', 'China', 'Chine', 'China', 'China', 'China', 'Κίνα', '中国', 'Sina', 'Kiina', 'Китай', '中国', 'Chiny', 'Kína', 'סין'),
(50, 'CX', 'Christmas Islan', 'Isola Christmas', 'Weihnachtsinsel', 'Île Christmas', 'Isla de Navidad', 'Ilha Christmas', 'Insula Christmas', 'Νήσος των Χριστουγέν', 'クリスマス島', 'Enez Christmas', 'Joulusaari', 'о-в Рождества', '圣诞岛', 'Wyspa Bożego Narodze', 'Karácsony-sziget', 'האי כריסטמס'),
(51, 'CC', 'Cocos (Keeling)', 'Isole Cocos (Ke', 'Kokosinseln', 'Îles Cocos', 'Islas Cocos', 'Ilhas Cocos (Keeling', 'Insulele Cocos (Keel', 'Νήσοι Κόκος (Κίλινγκ', 'ココス(キーリング)諸島', 'Inizi Kokoz', 'Kookossaaret (Keelin', 'Кокосовые о-ва', '科科斯（基林）群岛', 'Wyspy Kokosowe', 'Kókusz (Keeling)-szi', 'איי קוקוס (קילינג)'),
(52, 'CO', 'Colombia', 'Colombia', 'Kolumbien', 'Colombie', 'Colombia', 'Colômbia', 'Columbia', 'Κολομβία', 'コロンビア', 'Kolombia', 'Kolumbia', 'Колумбия', '哥伦比亚', 'Kolumbia', 'Kolumbia', 'קולומביה'),
(53, 'KM', 'Comoros', 'Comore', 'Komoren', 'Comores', 'Comoras', 'Comores', 'Comore', 'Κομόρες', 'コモロ', 'Komorez', 'Komorit', 'Коморы', '科摩罗', 'Komory', 'Comore-szigetek', 'קומורו'),
(54, 'CG', 'Congo - Brazzav', 'Congo-Brazzavil', 'Kongo-Brazzavil', 'Congo-Brazzavil', 'República del C', 'Congo - Brazzaville', 'Congo - Brazzaville', 'Κονγκό - Μπραζαβίλ', 'コンゴ共和国(ブラザビル)', 'Kongo - Brazzaville', 'Kongon tasavalta', 'Конго - Браззавиль', '刚果（布）', 'Kongo', 'Kongó - Brazzaville', 'קונגו - ברזאויל'),
(55, 'CD', 'Congo - Kinshas', 'Congo - Kinshas', 'Kongo-Kinshasa', 'Congo-Kinshasa', 'República Democ', 'Congo - Kinshasa', 'Congo - Kinshasa', 'Κονγκό - Κινσάσα', 'コンゴ民主共和国(キンシャサ)', 'Kongo - Kinshasa', 'Kongon demokraattine', 'Конго - Киншаса', '刚果（金）', 'Demokratyczna Republ', 'Kongó - Kinshasa', 'קונגו - קינשאסה'),
(56, 'CK', 'Cook Islands', 'Isole Cook', 'Cookinseln', 'Îles Cook', 'Islas Cook', 'Ilhas Cook', 'Insulele Cook', 'Νήσοι Κουκ', 'クック諸島', 'Inizi Cook', 'Cookinsaaret', 'Острова Кука', '库克群岛', 'Wyspy Cooka', 'Cook-szigetek', 'איי קוק'),
(57, 'CR', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Κόστα Ρίκα', 'コスタリカ', 'Costa Rica', 'Costa Rica', 'Коста-Рика', '哥斯达黎加', 'Kostaryka', 'Costa Rica', 'קוסטה ריקה'),
(58, 'CI', 'C', 'Costa d', 'Côte d’Ivoire', 'Côte d’Ivoire', 'Côte d’Ivoire', 'Costa do Marfim', 'Côte d’Ivoire', 'Ακτή Ελεφαντοστού', 'コートジボワール', 'Aod an Olifant', 'Norsunluurannikko', 'Кот-д’Ивуар', '科特迪瓦', 'Côte d’Ivoire', 'Elefántcsontpart', 'חוף השנהב'),
(59, 'HR', 'Croatia', 'Croazia', 'Kroatien', 'Croatie', 'Croacia', 'Croácia', 'Croația', 'Κροατία', 'クロアチア', 'Kroatia', 'Kroatia', 'Хорватия', '克罗地亚', 'Chorwacja', 'Horvátország', 'קרואטיה'),
(60, 'CU', 'Cuba', 'Cuba', 'Kuba', 'Cuba', 'Cuba', 'Cuba', 'Cuba', 'Κούβα', 'キューバ', 'Kuba', 'Kuuba', 'Куба', '古巴', 'Kuba', 'Kuba', 'קובה'),
(61, 'CW', 'Cura', 'Cura', 'Curaçao', 'Curaçao', 'Curazao', 'Curaçao', 'Curaçao', 'Κουρασάο', 'キュラソー', 'Curaçao', 'Curaçao', 'Кюрасао', '库拉索', 'Curaçao', 'Curaçao', 'קוראסאו'),
(62, 'CY', 'Cyprus', 'Cipro', 'Zypern', 'Chypre', 'Chipre', 'Chipre', 'Cipru', 'Κύπρος', 'キプロス', 'Kiprenez', 'Kypros', 'Кипр', '塞浦路斯', 'Cypr', 'Ciprus', 'קפריסין'),
(63, 'CZ', 'Czechia', 'C', 'Tschechien', 'Tchéquie', 'Chequia', 'Tchéquia', 'Cehia', 'Τσεχία', 'チェコ', 'Republik Tchek', 'Tšekinmaa', 'Чехия', '捷克', 'Czechy', 'Csehország', 'צ׳כיה'),
(64, 'DK', 'Denmark', 'Danimarca', 'Dänemark', 'Danemark', 'Dinamarca', 'Dinamarca', 'Danemarca', 'Δανία', 'デンマーク', 'Danmark', 'Tanska', 'Дания', '丹麦', 'Dania', 'Dánia', 'דנמרק'),
(65, 'DG', 'Diego Garcia', 'Diego Garcia', 'Diego Garcia', 'Diego Garcia', 'Diego García', 'Diego Garcia', 'Diego Garcia', 'Ντιέγκο Γκαρσία', 'ディエゴガルシア島', 'Diego Garcia', 'Diego Garcia', 'Диего-Гарсия', '迪戈加西亚岛', 'Diego Garcia', 'Diego Garcia', 'דייגו גרסיה'),
(66, 'DJ', 'Djibouti', 'Gibuti', 'Dschibuti', 'Djibouti', 'Yibuti', 'Djibuti', 'Djibouti', 'Τζιμπουτί', 'ジブチ', 'Djibouti', 'Djibouti', 'Джибути', '吉布提', 'Dżibuti', 'Dzsibuti', 'ג׳יבוטי'),
(67, 'DM', 'Dominica', 'Dominica', 'Dominica', 'Dominique', 'Dominica', 'Dominica', 'Dominica', 'Ντομίνικα', 'ドミニカ国', 'Dominica', 'Dominica', 'Доминика', '多米尼克', 'Dominika', 'Dominika', 'דומיניקה'),
(68, 'DO', 'Dominican Repub', 'Repubblica Domi', 'Dominikanische ', 'République domi', 'República Domin', 'República Dominicana', 'Republica Dominicană', 'Δομινικανή Δημοκρατί', 'ドミニカ共和国', 'Republik Dominikan', 'Dominikaaninen tasav', 'Доминиканская Респуб', '多米尼加共和国', 'Dominikana', 'Dominikai Köztársasá', 'הרפובליקה הדומיניקני'),
(69, 'EC', 'Ecuador', 'Ecuador', 'Ecuador', 'Équateur', 'Ecuador', 'Equador', 'Ecuador', 'Εκουαδόρ', 'エクアドル', 'Ecuador', 'Ecuador', 'Эквадор', '厄瓜多尔', 'Ekwador', 'Ecuador', 'אקוודור'),
(70, 'EG', 'Egypt', 'Egitto', 'Ägypten', 'Égypte', 'Egipto', 'Egito', 'Egipt', 'Αίγυπτος', 'エジプト', 'Egipt', 'Egypti', 'Египет', '埃及', 'Egipt', 'Egyiptom', 'מצרים'),
(71, 'SV', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'El Salvador', 'Ελ Σαλβαδόρ', 'エルサルバドル', 'Salvador', 'El Salvador', 'Сальвадор', '萨尔瓦多', 'Salwador', 'Salvador', 'אל סלבדור'),
(72, 'GQ', 'Equatorial Guin', 'Guinea Equatori', 'Äquatorialguine', 'Guinée équatori', 'Guinea Ecuatori', 'Guiné Equatorial', 'Guineea Ecuatorială', 'Ισημερινή Γουινέα', '赤道ギニア', 'Ginea ar Cʼheheder', 'Päiväntasaajan Guine', 'Экваториальная Гвине', '赤道几内亚', 'Gwinea Równikowa', 'Egyenlítői-Guinea', 'גינאה המשוונית'),
(73, 'ER', 'Eritrea', 'Eritrea', 'Eritrea', 'Érythrée', 'Eritrea', 'Eritreia', 'Eritreea', 'Ερυθραία', 'エリトリア', 'Eritrea', 'Eritrea', 'Эритрея', '厄立特里亚', 'Erytrea', 'Eritrea', 'אריתריאה'),
(74, 'EE', 'Estonia', 'Estonia', 'Estland', 'Estonie', 'Estonia', 'Estônia', 'Estonia', 'Εσθονία', 'エストニア', 'Estonia', 'Viro', 'Эстония', '爱沙尼亚', 'Estonia', 'Észtország', 'אסטוניה'),
(75, 'ET', 'Ethiopia', 'Etiopia', 'Äthiopien', 'Éthiopie', 'Etiopía', 'Etiópia', 'Etiopia', 'Αιθιοπία', 'エチオピア', 'Etiopia', 'Etiopia', 'Эфиопия', '埃塞俄比亚', 'Etiopia', 'Etiópia', 'אתיופיה'),
(76, 'EZ', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone', 'Eurozone'),
(77, 'FK', 'Falkland Island', 'Isole Falkland', 'Falklandinseln', 'Îles Malouines', 'Islas Malvinas', 'Ilhas Malvinas', 'Insulele Falkland', 'Νήσοι Φόκλαντ', 'フォークランド諸島', 'Inizi Falkland', 'Falklandinsaaret', 'Фолклендские о-ва', '福克兰群岛', 'Falklandy', 'Falkland-szigetek', 'איי פוקלנד'),
(78, 'FO', 'Faroe Islands', 'Isole F', 'Färöer', 'Îles Féroé', 'Islas Feroe', 'Ilhas Faroe', 'Insulele Feroe', 'Νήσοι Φερόες', 'フェロー諸島', 'Inizi Faero', 'Färsaaret', 'Фарерские о-ва', '法罗群岛', 'Wyspy Owcze', 'Feröer-szigetek', 'איי פארו'),
(79, 'FJ', 'Fiji', 'Figi', 'Fidschi', 'Fidji', 'Fiyi', 'Fiji', 'Fiji', 'Φίτζι', 'フィジー', 'Fidji', 'Fidži', 'Фиджи', '斐济', 'Fidżi', 'Fidzsi', 'פיג׳י'),
(80, 'FI', 'Finland', 'Finlandia', 'Finnland', 'Finlande', 'Finlandia', 'Finlândia', 'Finlanda', 'Φινλανδία', 'フィンランド', 'Finland', 'Suomi', 'Финляндия', '芬兰', 'Finlandia', 'Finnország', 'פינלנד'),
(81, 'FR', 'France', 'Francia', 'Frankreich', 'France', 'Francia', 'França', 'Franța', 'Γαλλία', 'フランス', 'Frañs', 'Ranska', 'Франция', '法国', 'Francja', 'Franciaország', 'צרפת'),
(82, 'GF', 'French Guiana', 'Guyana francese', 'Französisch-Gua', 'Guyane français', 'Guayana Frances', 'Guiana Francesa', 'Guyana Franceză', 'Γαλλική Γουιάνα', '仏領ギアナ', 'Gwiana cʼhall', 'Ranskan Guayana', 'Французская Гвиана', '法属圭亚那', 'Gujana Francuska', 'Francia Guyana', 'גיאנה הצרפתית'),
(83, 'PF', 'French Polynesi', 'Polinesia franc', 'Französisch-Pol', 'Polynésie franç', 'Polinesia Franc', 'Polinésia Francesa', 'Polinezia Franceză', 'Γαλλική Πολυνησία', '仏領ポリネシア', 'Polinezia Cʼhall', 'Ranskan Polynesia', 'Французская Полинези', '法属波利尼西亚', 'Polinezja Francuska', 'Francia Polinézia', 'פולינזיה הצרפתית'),
(84, 'TF', 'French Southern', 'Terre australi ', 'Französische Sü', 'Terres australe', 'Territorios Aus', 'Territórios Francese', 'Teritoriile Australe', 'Γαλλικές περιοχές το', '仏領極南諸島', 'Douaroù aostral Frañ', 'Ranskan eteläiset al', 'Французские Южные те', '法属南部领地', 'Francuskie Terytoria', 'Francia Déli Terület', 'הטריטוריות הדרומיות '),
(85, 'GA', 'Gabon', 'Gabon', 'Gabun', 'Gabon', 'Gabón', 'Gabão', 'Gabon', 'Γκαμπόν', 'ガボン', 'Gabon', 'Gabon', 'Габон', '加蓬', 'Gabon', 'Gabon', 'גבון'),
(86, 'GM', 'Gambia', 'Gambia', 'Gambia', 'Gambie', 'Gambia', 'Gâmbia', 'Gambia', 'Γκάμπια', 'ガンビア', 'Gambia', 'Gambia', 'Гамбия', '冈比亚', 'Gambia', 'Gambia', 'גמביה'),
(87, 'GE', 'Georgia', 'Georgia', 'Georgien', 'Géorgie', 'Georgia', 'Geórgia', 'Georgia', 'Γεωργία', 'ジョージア', 'Jorjia', 'Georgia', 'Грузия', '格鲁吉亚', 'Gruzja', 'Grúzia', 'גאורגיה'),
(88, 'DE', 'Germany', 'Germania', 'Deutschland', 'Allemagne', 'Alemania', 'Alemanha', 'Germania', 'Γερμανία', 'ドイツ', 'Alamagn', 'Saksa', 'Германия', '德国', 'Niemcy', 'Németország', 'גרמניה'),
(89, 'GH', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Ghana', 'Gana', 'Ghana', 'Γκάνα', 'ガーナ', 'Ghana', 'Ghana', 'Гана', '加纳', 'Ghana', 'Ghána', 'גאנה'),
(90, 'GI', 'Gibraltar', 'Gibilterra', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'Γιβραλτάρ', 'ジブラルタル', 'Jibraltar', 'Gibraltar', 'Гибралтар', '直布罗陀', 'Gibraltar', 'Gibraltár', 'גיברלטר'),
(91, 'GR', 'Greece', 'Grecia', 'Griechenland', 'Grèce', 'Grecia', 'Grécia', 'Grecia', 'Ελλάδα', 'ギリシャ', 'Gres', 'Kreikka', 'Греция', '希腊', 'Grecja', 'Görögország', 'יוון'),
(92, 'GL', 'Greenland', 'Groenlandia', 'Grönland', 'Groenland', 'Groenlandia', 'Groenlândia', 'Groenlanda', 'Γροιλανδία', 'グリーンランド', 'Greunland', 'Grönlanti', 'Гренландия', '格陵兰', 'Grenlandia', 'Grönland', 'גרינלנד'),
(93, 'GD', 'Grenada', 'Grenada', 'Grenada', 'Grenade', 'Granada', 'Granada', 'Grenada', 'Γρενάδα', 'グレナダ', 'Grenada', 'Grenada', 'Гренада', '格林纳达', 'Grenada', 'Grenada', 'גרנדה'),
(94, 'GP', 'Guadeloupe', 'Guadalupa', 'Guadeloupe', 'Guadeloupe', 'Guadalupe', 'Guadalupe', 'Guadelupa', 'Γουαδελούπη', 'グアドループ', 'Gwadeloup', 'Guadeloupe', 'Гваделупа', '瓜德罗普', 'Gwadelupa', 'Guadeloupe', 'גוואדלופ'),
(95, 'GU', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Guam', 'Γκουάμ', 'グアム', 'Guam', 'Guam', 'Гуам', '关岛', 'Guam', 'Guam', 'גואם'),
(96, 'GT', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Guatemala', 'Γουατεμάλα', 'グアテマラ', 'Guatemala', 'Guatemala', 'Гватемала', '危地马拉', 'Gwatemala', 'Guatemala', 'גואטמלה'),
(97, 'GG', 'Guernsey', 'Guernsey', 'Guernsey', 'Guernesey', 'Guernesey', 'Guernsey', 'Guernsey', 'Γκέρνζι', 'ガーンジー', 'Gwernenez', 'Guernsey', 'Гернси', '格恩西岛', 'Guernsey', 'Guernsey', 'גרנסי'),
(98, 'GN', 'Guinea', 'Guinea', 'Guinea', 'Guinée', 'Guinea', 'Guiné', 'Guineea', 'Γουινέα', 'ギニア', 'Ginea', 'Guinea', 'Гвинея', '几内亚', 'Gwinea', 'Guinea', 'גינאה'),
(99, 'GW', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinée-Bissau', 'Guinea-Bisáu', 'Guiné-Bissau', 'Guineea-Bissau', 'Γουινέα Μπισάου', 'ギニアビサウ', 'Ginea-Bissau', 'Guinea-Bissau', 'Гвинея-Бисау', '几内亚比绍', 'Gwinea Bissau', 'Bissau-Guinea', 'גינאה ביסאו'),
(100, 'GY', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'Guyana', 'Guiana', 'Guyana', 'Γουιάνα', 'ガイアナ', 'Guyana', 'Guyana', 'Гайана', '圭亚那', 'Gujana', 'Guyana', 'גיאנה'),
(101, 'HT', 'Haiti', 'Haiti', 'Haiti', 'Haïti', 'Haití', 'Haiti', 'Haiti', 'Αϊτή', 'ハイチ', 'Haiti', 'Haiti', 'Гаити', '海地', 'Haiti', 'Haiti', 'האיטי'),
(102, 'HN', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Honduras', 'Ονδούρα', 'ホンジュラス', 'Honduras', 'Honduras', 'Гондурас', '洪都拉斯', 'Honduras', 'Honduras', 'הונדורס'),
(103, 'HK', 'Hong Kong SAR C', 'RAS di Hong Kon', 'Sonderverwaltun', 'R.A.S. chinoise', 'RAE de Hong Kon', 'Hong Kong, RAE da Ch', 'R.A.S. Hong Kong a C', 'Χονγκ Κονγκ ΕΔΠ Κίνα', '中華人民共和国香港特別行政区', 'Hong Kong RMD Sina', 'Hongkong – Kiinan e.', 'Гонконг (специальный', '中国香港特别行政区', 'SRA Hongkong (Chiny)', 'Hongkong KKT', 'הונג קונג (מחוז מנהל'),
(104, 'HU', 'Hungary', 'Ungheria', 'Ungarn', 'Hongrie', 'Hungría', 'Hungria', 'Ungaria', 'Ουγγαρία', 'ハンガリー', 'Hungaria', 'Unkari', 'Венгрия', '匈牙利', 'Węgry', 'Magyarország', 'הונגריה'),
(105, 'IS', 'Iceland', 'Islanda', 'Island', 'Islande', 'Islandia', 'Islândia', 'Islanda', 'Ισλανδία', 'アイスランド', 'Island', 'Islanti', 'Исландия', '冰岛', 'Islandia', 'Izland', 'איסלנד'),
(106, 'IN', 'India', 'India', 'Indien', 'Inde', 'India', 'Índia', 'India', 'Ινδία', 'インド', 'India', 'Intia', 'Индия', '印度', 'Indie', 'India', 'הודו'),
(107, 'ID', 'Indonesia', 'Indonesia', 'Indonesien', 'Indonésie', 'Indonesia', 'Indonésia', 'Indonezia', 'Ινδονησία', 'インドネシア', 'Indonezia', 'Indonesia', 'Индонезия', '印度尼西亚', 'Indonezja', 'Indonézia', 'אינדונזיה'),
(108, 'IR', 'Iran', 'Iran', 'Iran', 'Iran', 'Irán', 'Irã', 'Iran', 'Ιράν', 'イラン', 'Iran', 'Iran', 'Иран', '伊朗', 'Iran', 'Irán', 'איראן'),
(109, 'IQ', 'Iraq', 'Iraq', 'Irak', 'Irak', 'Irak', 'Iraque', 'Irak', 'Ιράκ', 'イラク', 'Iraq', 'Irak', 'Ирак', '伊拉克', 'Irak', 'Irak', 'עיראק'),
(110, 'IE', 'Ireland', 'Irlanda', 'Irland', 'Irlande', 'Irlanda', 'Irlanda', 'Irlanda', 'Ιρλανδία', 'アイルランド', 'Iwerzhon', 'Irlanti', 'Ирландия', '爱尔兰', 'Irlandia', 'Írország', 'אירלנד'),
(111, 'IM', 'Isle of Man', 'Isola di Man', 'Isle of Man', 'Île de Man', 'Isla de Man', 'Ilha de Man', 'Insula Man', 'Νήσος Μαν', 'マン島', 'Enez Vanav', 'Mansaari', 'о-в Мэн', '马恩岛', 'Wyspa Man', 'Man-sziget', 'האי מאן'),
(112, 'IL', 'Israel', 'Israele', 'Israel', 'Israël', 'Israel', 'Israel', 'Israel', 'Ισραήλ', 'イスラエル', 'Israel', 'Israel', 'Израиль', '以色列', 'Izrael', 'Izrael', 'ישראל'),
(113, 'IT', 'Italy', 'Italia', 'Italien', 'Italie', 'Italia', 'Itália', 'Italia', 'Ιταλία', 'イタリア', 'Italia', 'Italia', 'Италия', '意大利', 'Włochy', 'Olaszország', 'איטליה'),
(114, 'JM', 'Jamaica', 'Giamaica', 'Jamaika', 'Jamaïque', 'Jamaica', 'Jamaica', 'Jamaica', 'Τζαμάικα', 'ジャマイカ', 'Jamaika', 'Jamaika', 'Ямайка', '牙买加', 'Jamajka', 'Jamaica', 'ג׳מייקה'),
(115, 'JP', 'Japan', 'Giappone', 'Japan', 'Japon', 'Japón', 'Japão', 'Japonia', 'Ιαπωνία', '日本', 'Japan', 'Japani', 'Япония', '日本', 'Japonia', 'Japán', 'יפן'),
(116, 'JE', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Jersey', 'Τζέρζι', 'ジャージー', 'Jerzenez', 'Jersey', 'Джерси', '泽西岛', 'Jersey', 'Jersey', 'ג׳רסי'),
(117, 'JO', 'Jordan', 'Giordania', 'Jordanien', 'Jordanie', 'Jordania', 'Jordânia', 'Iordania', 'Ιορδανία', 'ヨルダン', 'Jordania', 'Jordania', 'Иордания', '约旦', 'Jordania', 'Jordánia', 'ירדן'),
(118, 'KZ', 'Kazakhstan', 'Kazakistan', 'Kasachstan', 'Kazakhstan', 'Kazajistán', 'Cazaquistão', 'Kazahstan', 'Καζακστάν', 'カザフスタン', 'Kazakstan', 'Kazakstan', 'Казахстан', '哈萨克斯坦', 'Kazachstan', 'Kazahsztán', 'קזחסטן'),
(119, 'KE', 'Kenya', 'Kenya', 'Kenia', 'Kenya', 'Kenia', 'Quênia', 'Kenya', 'Κένυα', 'ケニア', 'Kenya', 'Kenia', 'Кения', '肯尼亚', 'Kenia', 'Kenya', 'קניה'),
(120, 'KI', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Kiribati', 'Quiribati', 'Kiribati', 'Κιριμπάτι', 'キリバス', 'Kiribati', 'Kiribati', 'Кирибати', '基里巴斯', 'Kiribati', 'Kiribati', 'קיריבאטי'),
(121, 'XK', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Kosovo', 'Κόσοβο', 'コソボ', 'Kosovo', 'Kosovo', 'Косово', '科索沃', 'Kosowo', 'Koszovó', 'קוסובו'),
(122, 'KW', 'Kuwait', 'Kuwait', 'Kuwait', 'Koweït', 'Kuwait', 'Kuwait', 'Kuweit', 'Κουβέιτ', 'クウェート', 'Koweit', 'Kuwait', 'Кувейт', '科威特', 'Kuwejt', 'Kuvait', 'כווית'),
(123, 'KG', 'Kyrgyzstan', 'Kirghizistan', 'Kirgisistan', 'Kirghizistan', 'Kirguistán', 'Quirguistão', 'Kârgâzstan', 'Κιργιστάν', 'キルギス', 'Kyrgyzstan', 'Kirgisia', 'Киргизия', '吉尔吉斯斯坦', 'Kirgistan', 'Kirgizisztán', 'קירגיזסטן'),
(124, 'LA', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Laos', 'Λάος', 'ラオス', 'Laos', 'Laos', 'Лаос', '老挝', 'Laos', 'Laosz', 'לאוס'),
(125, 'LV', 'Latvia', 'Lettonia', 'Lettland', 'Lettonie', 'Letonia', 'Letônia', 'Letonia', 'Λετονία', 'ラトビア', 'Latvia', 'Latvia', 'Латвия', '拉脱维亚', 'Łotwa', 'Lettország', 'לטביה'),
(126, 'LB', 'Lebanon', 'Libano', 'Libanon', 'Liban', 'Líbano', 'Líbano', 'Liban', 'Λίβανος', 'レバノン', 'Liban', 'Libanon', 'Ливан', '黎巴嫩', 'Liban', 'Libanon', 'לבנון'),
(127, 'LS', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesotho', 'Lesoto', 'Lesoto', 'Lesotho', 'Λεσότο', 'レソト', 'Lesotho', 'Lesotho', 'Лесото', '莱索托', 'Lesotho', 'Lesotho', 'לסוטו'),
(128, 'LR', 'Liberia', 'Liberia', 'Liberia', 'Libéria', 'Liberia', 'Libéria', 'Liberia', 'Λιβερία', 'リベリア', 'Liberia', 'Liberia', 'Либерия', '利比里亚', 'Liberia', 'Libéria', 'ליבריה'),
(129, 'LY', 'Libya', 'Libia', 'Libyen', 'Libye', 'Libia', 'Líbia', 'Libia', 'Λιβύη', 'リビア', 'Libia', 'Libya', 'Ливия', '利比亚', 'Libia', 'Líbia', 'לוב'),
(130, 'LI', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'Λιχτενστάιν', 'リヒテンシュタイン', 'Liechtenstein', 'Liechtenstein', 'Лихтенштейн', '列支敦士登', 'Liechtenstein', 'Liechtenstein', 'ליכטנשטיין'),
(131, 'LT', 'Lithuania', 'Lituania', 'Litauen', 'Lituanie', 'Lituania', 'Lituânia', 'Lituania', 'Λιθουανία', 'リトアニア', 'Lituania', 'Liettua', 'Литва', '立陶宛', 'Litwa', 'Litvánia', 'ליטא'),
(132, 'LU', 'Luxembourg', 'Lussemburgo', 'Luxemburg', 'Luxembourg', 'Luxemburgo', 'Luxemburgo', 'Luxemburg', 'Λουξεμβούργο', 'ルクセンブルク', 'Luksembourg', 'Luxemburg', 'Люксембург', '卢森堡', 'Luksemburg', 'Luxemburg', 'לוקסמבורג'),
(133, 'MO', 'Macau SAR China', 'RAS di Macao', 'Sonderverwaltun', 'R.A.S. chinoise', 'RAE de Macao (C', 'Macau, RAE da China', 'R.A.S. Macao a Chine', 'Μακάο ΕΔΠ Κίνας', '中華人民共和国マカオ特別行政区', 'Macau RMD Sina', 'Macao – Kiinan e.h.a', 'Макао (специальный а', '中国澳门特别行政区', 'SRA Makau (Chiny)', 'Makaó KKT', 'מקאו (מחוז מנהלי מיו'),
(134, 'MK', 'Macedonia', 'Repubblica di M', 'Mazedonien', 'Macédoine', 'Macedonia', 'Macedônia', 'Republica Macedonia', 'Πρώην Γιουγκοσλαβική', 'マケドニア', 'Makedonia', 'Makedonia', 'Македония', '马其顿', 'Macedonia', 'Macedónia', 'מקדוניה'),
(135, 'MG', 'Madagascar', 'Madagascar', 'Madagaskar', 'Madagascar', 'Madagascar', 'Madagascar', 'Madagascar', 'Μαδαγασκάρη', 'マダガスカル', 'Madagaskar', 'Madagaskar', 'Мадагаскар', '马达加斯加', 'Madagaskar', 'Madagaszkár', 'מדגסקר'),
(136, 'MW', 'Malawi', 'Malawi', 'Malawi', 'Malawi', 'Malaui', 'Malawi', 'Malawi', 'Μαλάουι', 'マラウイ', 'Malawi', 'Malawi', 'Малави', '马拉维', 'Malawi', 'Malawi', 'מלאווי'),
(137, 'MY', 'Malaysia', 'Malaysia', 'Malaysia', 'Malaisie', 'Malasia', 'Malásia', 'Malaysia', 'Μαλαισία', 'マレーシア', 'Malaysia', 'Malesia', 'Малайзия', '马来西亚', 'Malezja', 'Malajzia', 'מלזיה'),
(138, 'MV', 'Maldives', 'Maldive', 'Malediven', 'Maldives', 'Maldivas', 'Maldivas', 'Maldive', 'Μαλδίβες', 'モルディブ', 'Maldivez', 'Malediivit', 'Мальдивы', '马尔代夫', 'Malediwy', 'Maldív-szigetek', 'האיים המלדיביים'),
(139, 'ML', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'Mali', 'Μάλι', 'マリ', 'Mali', 'Mali', 'Мали', '马里', 'Mali', 'Mali', 'מאלי'),
(140, 'MT', 'Malta', 'Malta', 'Malta', 'Malte', 'Malta', 'Malta', 'Malta', 'Μάλτα', 'マルタ', 'Malta', 'Malta', 'Мальта', '马耳他', 'Malta', 'Málta', 'מלטה'),
(141, 'MH', 'Marshall Island', 'Isole Marshall', 'Marshallinseln', 'Îles Marshall', 'Islas Marshall', 'Ilhas Marshall', 'Insulele Marshall', 'Νήσοι Μάρσαλ', 'マーシャル諸島', 'Inizi Marshall', 'Marshallinsaaret', 'Маршалловы Острова', '马绍尔群岛', 'Wyspy Marshalla', 'Marshall-szigetek', 'איי מרשל'),
(142, 'MQ', 'Martinique', 'Martinica', 'Martinique', 'Martinique', 'Martinica', 'Martinica', 'Martinica', 'Μαρτινίκα', 'マルティニーク', 'Martinik', 'Martinique', 'Мартиника', '马提尼克', 'Martynika', 'Martinique', 'מרטיניק'),
(143, 'MR', 'Mauritania', 'Mauritania', 'Mauretanien', 'Mauritanie', 'Mauritania', 'Mauritânia', 'Mauritania', 'Μαυριτανία', 'モーリタニア', 'Maouritania', 'Mauritania', 'Мавритания', '毛里塔尼亚', 'Mauretania', 'Mauritánia', 'מאוריטניה'),
(144, 'MU', 'Mauritius', 'Mauritius', 'Mauritius', 'Maurice', 'Mauricio', 'Maurício', 'Mauritius', 'Μαυρίκιος', 'モーリシャス', 'Moris', 'Mauritius', 'Маврикий', '毛里求斯', 'Mauritius', 'Mauritius', 'מאוריציוס'),
(145, 'YT', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Mayotte', 'Μαγιότ', 'マヨット島', 'Mayotte', 'Mayotte', 'Майотта', '马约特', 'Majotta', 'Mayotte', 'מאיוט'),
(146, 'MX', 'Mexico', 'Messico', 'Mexiko', 'Mexique', 'México', 'México', 'Mexic', 'Μεξικό', 'メキシコ', 'Mecʼhiko', 'Meksiko', 'Мексика', '墨西哥', 'Meksyk', 'Mexikó', 'מקסיקו'),
(147, 'FM', 'Micronesia', 'Micronesia', 'Mikronesien', 'États fédérés d', 'Micronesia', 'Micronésia', 'Micronezia', 'Μικρονησία', 'ミクロネシア連邦', 'Mikronezia', 'Mikronesian liittova', 'Федеративные Штаты М', '密克罗尼西亚', 'Mikronezja', 'Mikronézia', 'מיקרונזיה'),
(148, 'MD', 'Moldova', 'Moldavia', 'Republik Moldau', 'Moldavie', 'Moldavia', 'Moldávia', 'Republica Moldova', 'Μολδαβία', 'モルドバ', 'Moldova', 'Moldova', 'Молдова', '摩尔多瓦', 'Mołdawia', 'Moldova', 'מולדובה'),
(149, 'MC', 'Monaco', 'Monaco', 'Monaco', 'Monaco', 'Mónaco', 'Mônaco', 'Monaco', 'Μονακό', 'モナコ', 'Monaco', 'Monaco', 'Монако', '摩纳哥', 'Monako', 'Monaco', 'מונקו'),
(150, 'MN', 'Mongolia', 'Mongolia', 'Mongolei', 'Mongolie', 'Mongolia', 'Mongólia', 'Mongolia', 'Μογγολία', 'モンゴル', 'Mongolia', 'Mongolia', 'Монголия', '蒙古', 'Mongolia', 'Mongólia', 'מונגוליה'),
(151, 'ME', 'Montenegro', 'Montenegro', 'Montenegro', 'Monténégro', 'Montenegro', 'Montenegro', 'Muntenegru', 'Μαυροβούνιο', 'モンテネグロ', 'Montenegro', 'Montenegro', 'Черногория', '黑山', 'Czarnogóra', 'Montenegró', 'מונטנגרו'),
(152, 'MS', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Montserrat', 'Μονσεράτ', 'モントセラト', 'Montserrat', 'Montserrat', 'Монтсеррат', '蒙特塞拉特', 'Montserrat', 'Montserrat', 'מונסראט'),
(153, 'MA', 'Morocco', 'Marocco', 'Marokko', 'Maroc', 'Marruecos', 'Marrocos', 'Maroc', 'Μαρόκο', 'モロッコ', 'Maroko', 'Marokko', 'Марокко', '摩洛哥', 'Maroko', 'Marokkó', 'מרוקו'),
(154, 'MZ', 'Mozambique', 'Mozambico', 'Mosambik', 'Mozambique', 'Mozambique', 'Moçambique', 'Mozambic', 'Μοζαμβίκη', 'モザンビーク', 'Mozambik', 'Mosambik', 'Мозамбик', '莫桑比克', 'Mozambik', 'Mozambik', 'מוזמביק'),
(155, 'MM', 'Myanmar (Burma)', 'Myanmar (Birman', 'Myanmar', 'Myanmar (Birman', 'Myanmar (Birman', 'Mianmar (Birmânia)', 'Myanmar (Birmania)', 'Μιανμάρ/Βιρμανία', 'ミャンマー', 'Myanmar (Birmania)', 'Myanmar (Burma)', 'Мьянма (Бирма)', '缅甸', 'Mjanma (Birma)', 'Mianmar (Burma)', 'מיאנמר (בורמה)'),
(156, 'NA', 'Namibia', 'Namibia', 'Namibia', 'Namibie', 'Namibia', 'Namíbia', 'Namibia', 'Ναμίμπια', 'ナミビア', 'Namibia', 'Namibia', 'Намибия', '纳米比亚', 'Namibia', 'Namíbia', 'נמיביה'),
(157, 'NR', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Nauru', 'Ναουρού', 'ナウル', 'Nauru', 'Nauru', 'Науру', '瑙鲁', 'Nauru', 'Nauru', 'נאורו'),
(158, 'NP', 'Nepal', 'Nepal', 'Nepal', 'Népal', 'Nepal', 'Nepal', 'Nepal', 'Νεπάλ', 'ネパール', 'Nepal', 'Nepal', 'Непал', '尼泊尔', 'Nepal', 'Nepál', 'נפאל'),
(159, 'NL', 'Netherlands', 'Paesi Bassi', 'Niederlande', 'Pays-Bas', 'Países Bajos', 'Holanda', 'Țările de Jos', 'Ολλανδία', 'オランダ', 'Izelvroioù', 'Alankomaat', 'Нидерланды', '荷兰', 'Holandia', 'Hollandia', 'הולנד'),
(160, 'NC', 'New Caledonia', 'Nuova Caledonia', 'Neukaledonien', 'Nouvelle-Calédo', 'Nueva Caledonia', 'Nova Caledônia', 'Noua Caledonie', 'Νέα Καληδονία', 'ニューカレドニア', 'Kaledonia Nevez', 'Uusi-Kaledonia', 'Новая Каледония', '新喀里多尼亚', 'Nowa Kaledonia', 'Új-Kaledónia', 'קלדוניה החדשה'),
(161, 'NZ', 'New Zealand', 'Nuova Zelanda', 'Neuseeland', 'Nouvelle-Zéland', 'Nueva Zelanda', 'Nova Zelândia', 'Noua Zeelandă', 'Νέα Ζηλανδία', 'ニュージーランド', 'Zeland-Nevez', 'Uusi-Seelanti', 'Новая Зеландия', '新西兰', 'Nowa Zelandia', 'Új-Zéland', 'ניו זילנד'),
(162, 'NI', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'Nicarágua', 'Nicaragua', 'Νικαράγουα', 'ニカラグア', 'Nicaragua', 'Nicaragua', 'Никарагуа', '尼加拉瓜', 'Nikaragua', 'Nicaragua', 'ניקרגואה'),
(163, 'NE', 'Niger', 'Niger', 'Niger', 'Niger', 'Níger', 'Níger', 'Niger', 'Νίγηρας', 'ニジェール', 'Niger', 'Niger', 'Нигер', '尼日尔', 'Niger', 'Niger', 'ניז׳ר'),
(164, 'NG', 'Nigeria', 'Nigeria', 'Nigeria', 'Nigéria', 'Nigeria', 'Nigéria', 'Nigeria', 'Νιγηρία', 'ナイジェリア', 'Nigeria', 'Nigeria', 'Нигерия', '尼日利亚', 'Nigeria', 'Nigéria', 'ניגריה'),
(165, 'NU', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Niue', 'Νιούε', 'ニウエ', 'Niue', 'Niue', 'Ниуэ', '纽埃', 'Niue', 'Niue', 'ניווה'),
(166, 'NF', 'Norfolk Island', 'Isola Norfolk', 'Norfolkinsel', 'Île Norfolk', 'Isla Norfolk', 'Ilha Norfolk', 'Insula Norfolk', 'Νήσος Νόρφολκ', 'ノーフォーク島', 'Enez Norfolk', 'Norfolkinsaari', 'о-в Норфолк', '诺福克岛', 'Norfolk', 'Norfolk-sziget', 'איי נורפוק'),
(167, 'KP', 'North Korea', 'Corea del Nord', 'Nordkorea', 'Corée du Nord', 'Corea del Norte', 'Coreia do Norte', 'Coreea de Nord', 'Βόρεια Κορέα', '朝鮮民主主義人民共和国', 'Korea an Norzh', 'Pohjois-Korea', 'КНДР', '朝鲜', 'Korea Północna', 'Észak-Korea', 'קוריאה הצפונית'),
(168, 'MP', 'Northern Marian', 'Isole Marianne ', 'Nördliche Maria', 'Îles Mariannes ', 'Islas Marianas ', 'Ilhas Marianas do No', 'Insulele Mariane de ', 'Νήσοι Βόρειες Μαριάν', '北マリアナ諸島', 'Inizi Mariana an Nor', 'Pohjois-Mariaanit', 'Северные Марианские ', '北马里亚纳群岛', 'Mariany Północne', 'Északi Mariana-szige', 'איי מריאנה הצפוניים'),
(169, 'NO', 'Norway', 'Norvegia', 'Norwegen', 'Norvège', 'Noruega', 'Noruega', 'Norvegia', 'Νορβηγία', 'ノルウェー', 'Norvegia', 'Norja', 'Норвегия', '挪威', 'Norwegia', 'Norvégia', 'נורווגיה'),
(170, 'OM', 'Oman', 'Oman', 'Oman', 'Oman', 'Omán', 'Omã', 'Oman', 'Ομάν', 'オマーン', 'Oman', 'Oman', 'Оман', '阿曼', 'Oman', 'Omán', 'עומאן'),
(171, 'PK', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistan', 'Pakistán', 'Paquistão', 'Pakistan', 'Πακιστάν', 'パキスタン', 'Pakistan', 'Pakistan', 'Пакистан', '巴基斯坦', 'Pakistan', 'Pakisztán', 'פקיסטן'),
(172, 'PW', 'Palau', 'Palau', 'Palau', 'Palaos', 'Palaos', 'Palau', 'Palau', 'Παλάου', 'パラオ', 'Palau', 'Palau', 'Палау', '帕劳', 'Palau', 'Palau', 'פלאו'),
(173, 'PS', 'Palestinian Ter', 'Territori pales', 'Palästinensisch', 'Territoires pal', 'Territorios Pal', 'Territórios palestin', 'Teritoriile Palestin', 'Παλαιστινιακά Εδάφη', 'パレスチナ自治区', 'Tiriadoù Palestina', 'Palestiinalaisalueet', 'Палестинские террито', '巴勒斯坦领土', 'Terytoria Palestyńsk', 'Palesztin Terület', 'השטחים הפלסטיניים'),
(174, 'PA', 'Panama', 'Panam', 'Panama', 'Panama', 'Panamá', 'Panamá', 'Panama', 'Παναμάς', 'パナマ', 'Panamá', 'Panama', 'Панама', '巴拿马', 'Panama', 'Panama', 'פנמה'),
(175, 'PG', 'Papua New Guine', 'Papua Nuova Gui', 'Papua-Neuguinea', 'Papouasie-Nouve', 'Papúa Nueva Gui', 'Papua-Nova Guiné', 'Papua-Noua Guinee', 'Παπούα Νέα Γουινέα', 'パプアニューギニア', 'Papoua Ginea-Nevez', 'Papua-Uusi-Guinea', 'Папуа – Новая Гвинея', '巴布亚新几内亚', 'Papua-Nowa Gwinea', 'Pápua Új-Guinea', 'פפואה גינאה החדשה'),
(176, 'PY', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguay', 'Paraguai', 'Paraguay', 'Παραγουάη', 'パラグアイ', 'Paraguay', 'Paraguay', 'Парагвай', '巴拉圭', 'Paragwaj', 'Paraguay', 'פרגוואי'),
(177, 'PE', 'Peru', 'Per', 'Peru', 'Pérou', 'Perú', 'Peru', 'Peru', 'Περού', 'ペルー', 'Perou', 'Peru', 'Перу', '秘鲁', 'Peru', 'Peru', 'פרו'),
(178, 'PH', 'Philippines', 'Filippine', 'Philippinen', 'Philippines', 'Filipinas', 'Filipinas', 'Filipine', 'Φιλιππίνες', 'フィリピン', 'Filipinez', 'Filippiinit', 'Филиппины', '菲律宾', 'Filipiny', 'Fülöp-szigetek', 'הפיליפינים'),
(179, 'PN', 'Pitcairn Island', 'Isole Pitcairn', 'Pitcairninseln', 'Îles Pitcairn', 'Islas Pitcairn', 'Ilhas Pitcairn', 'Insulele Pitcairn', 'Νήσοι Πίτκερν', 'ピトケアン諸島', 'Enez Pitcairn', 'Pitcairn', 'острова Питкэрн', '皮特凯恩群岛', 'Pitcairn', 'Pitcairn-szigetek', 'איי פיטקרן'),
(180, 'PL', 'Poland', 'Polonia', 'Polen', 'Pologne', 'Polonia', 'Polônia', 'Polonia', 'Πολωνία', 'ポーランド', 'Polonia', 'Puola', 'Польша', '波兰', 'Polska', 'Lengyelország', 'פולין'),
(181, 'PT', 'Portugal', 'Portogallo', 'Portugal', 'Portugal', 'Portugal', 'Portugal', 'Portugalia', 'Πορτογαλία', 'ポルトガル', 'Portugal', 'Portugali', 'Португалия', '葡萄牙', 'Portugalia', 'Portugália', 'פורטוגל'),
(182, 'PR', 'Puerto Rico', 'Portorico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'Porto Rico', 'Puerto Rico', 'Πουέρτο Ρίκο', 'プエルトリコ', 'Puerto Rico', 'Puerto Rico', 'Пуэрто-Рико', '波多黎各', 'Portoryko', 'Puerto Rico', 'פוארטו ריקו'),
(183, 'QA', 'Qatar', 'Qatar', 'Katar', 'Qatar', 'Catar', 'Catar', 'Qatar', 'Κατάρ', 'カタール', 'Qatar', 'Qatar', 'Катар', '卡塔尔', 'Katar', 'Katar', 'קטאר'),
(184, 'RE', 'R', 'Riunione', 'Réunion', 'La Réunion', 'Reunión', 'Reunião', 'Réunion', 'Ρεϊνιόν', 'レユニオン島', 'Ar Reünion', 'Réunion', 'Реюньон', '留尼汪', 'Reunion', 'Réunion', 'ראוניון'),
(185, 'RO', 'Romania', 'Romania', 'Rumänien', 'Roumanie', 'Rumanía', 'Romênia', 'România', 'Ρουμανία', 'ルーマニア', 'Roumania', 'Romania', 'Румыния', '罗马尼亚', 'Rumunia', 'Románia', 'רומניה'),
(186, 'RU', 'Russia', 'Russia', 'Russland', 'Russie', 'Rusia', 'Rússia', 'Rusia', 'Ρωσία', 'ロシア', 'Rusia', 'Venäjä', 'Россия', '俄罗斯', 'Rosja', 'Oroszország', 'רוסיה'),
(187, 'RW', 'Rwanda', 'Ruanda', 'Ruanda', 'Rwanda', 'Ruanda', 'Ruanda', 'Rwanda', 'Ρουάντα', 'ルワンダ', 'Rwanda', 'Ruanda', 'Руанда', '卢旺达', 'Rwanda', 'Ruanda', 'רואנדה'),
(188, 'WS', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Samoa', 'Σαμόα', 'サモア', 'Samoa', 'Samoa', 'Самоа', '萨摩亚', 'Samoa', 'Szamoa', 'סמואה'),
(189, 'SM', 'San Marino', 'San Marino', 'San Marino', 'Saint-Marin', 'San Marino', 'San Marino', 'San Marino', 'Άγιος Μαρίνος', 'サンマリノ', 'San Marino', 'San Marino', 'Сан-Марино', '圣马力诺', 'San Marino', 'San Marino', 'סן מרינו'),
(190, 'ST', 'S', 'S', 'São Tomé und Pr', 'Sao Tomé-et-Pri', 'Santo Tomé y Pr', 'São Tomé e Príncipe', 'Sao Tomé și Príncipe', 'Σάο Τομέ και Πρίνσιπ', 'サントメ・プリンシペ', 'São Tomé ha Príncipe', 'São Tomé ja Príncipe', 'Сан-Томе и Принсипи', '圣多美和普林西比', 'Wyspy Świętego Tomas', 'Sao Tomé és Príncipe', 'סאו טומה ופרינסיפה'),
(191, 'SA', 'Saudi Arabia', 'Arabia Saudita', 'Saudi-Arabien', 'Arabie saoudite', 'Arabia Saudí', 'Arábia Saudita', 'Arabia Saudită', 'Σαουδική Αραβία', 'サウジアラビア', 'Arabia Saoudat', 'Saudi-Arabia', 'Саудовская Аравия', '沙特阿拉伯', 'Arabia Saudyjska', 'Szaúd-Arábia', 'ערב הסעודית'),
(192, 'SN', 'Senegal', 'Senegal', 'Senegal', 'Sénégal', 'Senegal', 'Senegal', 'Senegal', 'Σενεγάλη', 'セネガル', 'Senegal', 'Senegal', 'Сенегал', '塞内加尔', 'Senegal', 'Szenegál', 'סנגל'),
(193, 'RS', 'Serbia', 'Serbia', 'Serbien', 'Serbie', 'Serbia', 'Sérvia', 'Serbia', 'Σερβία', 'セルビア', 'Serbia', 'Serbia', 'Сербия', '塞尔维亚', 'Serbia', 'Szerbia', 'סרביה'),
(194, 'SC', 'Seychelles', 'Seychelles', 'Seychellen', 'Seychelles', 'Seychelles', 'Seicheles', 'Seychelles', 'Σεϋχέλλες', 'セーシェル', 'Sechelez', 'Seychellit', 'Сейшельские Острова', '塞舌尔', 'Seszele', 'Seychelle-szigetek', 'איי סיישל'),
(195, 'SL', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'Serra Leoa', 'Sierra Leone', 'Σιέρα Λεόνε', 'シエラレオネ', 'Sierra Leone', 'Sierra Leone', 'Сьерра-Леоне', '塞拉利昂', 'Sierra Leone', 'Sierra Leone', 'סיירה לאונה'),
(196, 'SG', 'Singapore', 'Singapore', 'Singapur', 'Singapour', 'Singapur', 'Cingapura', 'Singapore', 'Σιγκαπούρη', 'シンガポール', 'Singapour', 'Singapore', 'Сингапур', '新加坡', 'Singapur', 'Szingapúr', 'סינגפור'),
(197, 'SX', 'Sint Maarten', 'Sint Maarten', 'Sint Maarten', 'Saint-Martin (p', 'Sint Maarten', 'Sint Maarten', 'Sint-Maarten', 'Άγιος Μαρτίνος (Ολλα', 'シント・マールテン', 'Sint Maarten', 'Sint Maarten', 'Синт-Мартен', '荷属圣马丁', 'Sint Maarten', 'Sint Maarten', 'סנט מארטן'),
(198, 'SK', 'Slovakia', 'Slovacchia', 'Slowakei', 'Slovaquie', 'Eslovaquia', 'Eslováquia', 'Slovacia', 'Σλοβακία', 'スロバキア', 'Slovakia', 'Slovakia', 'Словакия', '斯洛伐克', 'Słowacja', 'Szlovákia', 'סלובקיה'),
(199, 'SI', 'Slovenia', 'Slovenia', 'Slowenien', 'Slovénie', 'Eslovenia', 'Eslovênia', 'Slovenia', 'Σλοβενία', 'スロベニア', 'Slovenia', 'Slovenia', 'Словения', '斯洛文尼亚', 'Słowenia', 'Szlovénia', 'סלובניה'),
(200, 'SB', 'Solomon Islands', 'Isole Salomone', 'Salomonen', 'Îles Salomon', 'Islas Salomón', 'Ilhas Salomão', 'Insulele Solomon', 'Νήσοι Σολομώντος', 'ソロモン諸島', 'Inizi Salomon', 'Salomonsaaret', 'Соломоновы Острова', '所罗门群岛', 'Wyspy Salomona', 'Salamon-szigetek', 'איי שלמה'),
(201, 'SO', 'Somalia', 'Somalia', 'Somalia', 'Somalie', 'Somalia', 'Somália', 'Somalia', 'Σομαλία', 'ソマリア', 'Somalia', 'Somalia', 'Сомали', '索马里', 'Somalia', 'Szomália', 'סומליה'),
(202, 'ZA', 'South Africa', 'Sudafrica', 'Südafrika', 'Afrique du Sud', 'Sudáfrica', 'África do Sul', 'Africa de Sud', 'Νότια Αφρική', '南アフリカ', 'Suafrika', 'Etelä-Afrikka', 'ЮАР', '南非', 'Republika Południowe', 'Dél-afrikai Köztársa', 'דרום אפריקה'),
(203, 'GS', 'South Georgia &', 'Georgia del Sud', 'Südgeorgien und', 'Géorgie du Sud ', 'Islas Georgia d', 'Ilhas Geórgia do Sul', 'Georgia de Sud și In', 'Νήσοι Νότια Γεωργία ', '南ジョージア島・南サンドイッチ諸島', 'Inizi Georgia ar Su ', 'Etelä-Georgia ja Ete', 'Южная Георгия и Южны', '南乔治亚和南桑威奇群岛', 'Georgia Południowa i', 'Déli-Georgia és Déli', 'ג׳ורג׳יה הדרומית ואי'),
(204, 'KR', 'South Korea', 'Corea del Sud', 'Südkorea', 'Corée du Sud', 'Corea del Sur', 'Coreia do Sul', 'Coreea de Sud', 'Νότια Κορέα', '大韓民国', 'Korea ar Su', 'Etelä-Korea', 'Республика Корея', '韩国', 'Korea Południowa', 'Dél-Korea', 'קוריאה הדרומית'),
(205, 'SS', 'South Sudan', 'Sud Sudan', 'Südsudan', 'Soudan du Sud', 'Sudán del Sur', 'Sudão do Sul', 'Sudanul de Sud', 'Νότιο Σουδάν', '南スーダン', 'Susoudan', 'Etelä-Sudan', 'Южный Судан', '南苏丹', 'Sudan Południowy', 'Dél-Szudán', 'דרום סודן'),
(206, 'ES', 'Spain', 'Spagna', 'Spanien', 'Espagne', 'España', 'Espanha', 'Spania', 'Ισπανία', 'スペイン', 'Spagn', 'Espanja', 'Испания', '西班牙', 'Hiszpania', 'Spanyolország', 'ספרד'),
(207, 'LK', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Σρι Λάνκα', 'スリランカ', 'Sri Lanka', 'Sri Lanka', 'Шри-Ланка', '斯里兰卡', 'Sri Lanka', 'Srí Lanka', 'סרי לנקה'),
(208, 'BL', 'St. Barth', 'Saint-Barth', 'St. Barthélemy', 'Saint-Barthélem', 'San Bartolomé', 'São Bartolomeu', 'Sfântul Bartolomeu', 'Άγιος Βαρθολομαίος', 'サン・バルテルミー島', 'Saint Barthélemy', 'Saint-Barthélemy', 'Сен-Бартелеми', '圣巴泰勒米', 'Saint-Barthélemy', 'Saint-Barthélemy', 'סנט ברתולומיאו'),
(209, 'SH', 'St. Helena', 'Sant', 'St. Helena', 'Sainte-Hélène', 'Santa Elena', 'Santa Helena', 'Sfânta Elena', 'Αγία Ελένη', 'セントヘレナ', 'Saint-Helena', 'Saint Helena', 'о-в Св. Елены', '圣赫勒拿', 'Wyspa Świętej Heleny', 'Szent Ilona', 'סנט הלנה'),
(210, 'KN', 'St. Kitts & Nev', 'Saint Kitts e N', 'St. Kitts und N', 'Saint-Christoph', 'San Cristóbal y', 'São Cristóvão e Nevi', 'Saint Kitts și Nevis', 'Άγιος Χριστόφορος κα', 'セントクリストファー・ネーヴィス', 'Saint Kitts ha Nevis', 'Saint Kitts ja Nevis', 'Сент-Китс и Невис', '圣基茨和尼维斯', 'Saint Kitts i Nevis', 'Saint Kitts és Nevis', 'סנט קיטס ונוויס'),
(211, 'LC', 'St. Lucia', 'Saint Lucia', 'St. Lucia', 'Sainte-Lucie', 'Santa Lucía', 'Santa Lúcia', 'Sfânta Lucia', 'Αγία Λουκία', 'セントルシア', 'Saint Lucia', 'Saint Lucia', 'Сент-Люсия', '圣卢西亚', 'Saint Lucia', 'Saint Lucia', 'סנט לוסיה'),
(212, 'MF', 'St. Martin', 'Saint Martin', 'St. Martin', 'Saint-Martin', 'San Martín', 'São Martinho', 'Sfântul Martin', 'Άγιος Μαρτίνος (Γαλλ', 'サン・マルタン', 'Saint Martin', 'Saint-Martin', 'Сен-Мартен', '圣马丁岛', 'Saint-Martin', 'Saint Martin', 'סן מרטן'),
(213, 'PM', 'St. Pierre & Mi', 'Saint Pierre e ', 'St. Pierre und ', 'Saint-Pierre-et', 'San Pedro y Miq', 'Saint Pierre e Mique', 'Saint-Pierre și Miqu', 'Σεν Πιερ και Μικελόν', 'サンピエール島・ミクロン島', 'Sant-Pêr-ha-Mikelon', 'Saint-Pierre ja Miqu', 'Сен-Пьер и Микелон', '圣皮埃尔和密克隆群岛', 'Saint-Pierre i Mique', 'Saint-Pierre és Miqu', 'סנט פייר ומיקלון'),
(214, 'VC', 'St. Vincent & G', 'Saint Vincent e', 'St. Vincent und', 'Saint-Vincent-e', 'San Vicente y l', 'São Vicente e Granad', 'Saint Vincent și Gre', 'Άγιος Βικέντιος και ', 'セントビンセント及びグレナディーン諸島', 'Sant Visant hag ar G', 'Saint Vincent ja Gre', 'Сент-Винсент и Грена', '圣文森特和格林纳丁斯', 'Saint Vincent i Gren', 'Saint Vincent és a G', 'סנט וינסנט והגרנדיני'),
(215, 'SD', 'Sudan', 'Sudan', 'Sudan', 'Soudan', 'Sudán', 'Sudão', 'Sudan', 'Σουδάν', 'スーダン', 'Soudan', 'Sudan', 'Судан', '苏丹', 'Sudan', 'Szudán', 'סודן'),
(216, 'SR', 'Suriname', 'Suriname', 'Suriname', 'Suriname', 'Surinam', 'Suriname', 'Suriname', 'Σουρινάμ', 'スリナム', 'Surinam', 'Suriname', 'Суринам', '苏里南', 'Surinam', 'Suriname', 'סורינם'),
(217, 'SJ', 'Svalbard & Jan ', 'Svalbard e Jan ', 'Spitzbergen', 'Svalbard et Jan', 'Svalbard y Jan ', 'Svalbard e Jan Mayen', 'Svalbard și Jan Maye', 'Σβάλμπαρντ και Γιαν ', 'スバールバル諸島・ヤンマイエン島', 'Svalbard', 'Huippuvuoret ja Jan ', 'Шпицберген и Ян-Майе', '斯瓦尔巴和扬马延', 'Svalbard i Jan Mayen', 'Svalbard és Jan Maye', 'סוולבארד ויאן מאיין'),
(218, 'SZ', 'Swaziland', 'Swaziland', 'Swasiland', 'Swaziland', 'Suazilandia', 'Suazilândia', 'Swaziland', 'Σουαζιλάνδη', 'スワジランド', 'Swaziland', 'Swazimaa', 'Свазиленд', '斯威士兰', 'Suazi', 'Szváziföld', 'סווזילנד'),
(219, 'SE', 'Sweden', 'Svezia', 'Schweden', 'Suède', 'Suecia', 'Suécia', 'Suedia', 'Σουηδία', 'スウェーデン', 'Sveden', 'Ruotsi', 'Швеция', '瑞典', 'Szwecja', 'Svédország', 'שוודיה'),
(220, 'CH', 'Switzerland', 'Svizzera', 'Schweiz', 'Suisse', 'Suiza', 'Suíça', 'Elveția', 'Ελβετία', 'スイス', 'Suis', 'Sveitsi', 'Швейцария', '瑞士', 'Szwajcaria', 'Svájc', 'שווייץ'),
(221, 'SY', 'Syria', 'Siria', 'Syrien', 'Syrie', 'Siria', 'Síria', 'Siria', 'Συρία', 'シリア', 'Siria', 'Syyria', 'Сирия', '叙利亚', 'Syria', 'Szíria', 'סוריה'),
(222, 'TW', 'Taiwan', 'Taiwan', 'Taiwan', 'Taïwan', 'Taiwán', 'Taiwan', 'Taiwan', 'Ταϊβάν', '台湾', 'Taiwan', 'Taiwan', 'Тайвань', '台湾', 'Tajwan', 'Tajvan', 'טייוואן'),
(223, 'TJ', 'Tajikistan', 'Tagikistan', 'Tadschikistan', 'Tadjikistan', 'Tayikistán', 'Tajiquistão', 'Tadjikistan', 'Τατζικιστάν', 'タジキスタン', 'Tadjikistan', 'Tadžikistan', 'Таджикистан', '塔吉克斯坦', 'Tadżykistan', 'Tádzsikisztán', 'טג׳יקיסטן'),
(224, 'TZ', 'Tanzania', 'Tanzania', 'Tansania', 'Tanzanie', 'Tanzania', 'Tanzânia', 'Tanzania', 'Τανζανία', 'タンザニア', 'Tanzania', 'Tansania', 'Танзания', '坦桑尼亚', 'Tanzania', 'Tanzánia', 'טנזניה'),
(225, 'TH', 'Thailand', 'Thailandia', 'Thailand', 'Thaïlande', 'Tailandia', 'Tailândia', 'Thailanda', 'Ταϊλάνδη', 'タイ', 'Thailand', 'Thaimaa', 'Таиланд', '泰国', 'Tajlandia', 'Thaiföld', 'תאילנד'),
(226, 'TL', 'Timor-Leste', 'Timor Est', 'Osttimor', 'Timor oriental', 'Timor-Leste', 'Timor-Leste', 'Timorul de Est', 'Τιμόρ-Λέστε', '東ティモール', 'Timor-Leste', 'Itä-Timor', 'Восточный Тимор', '东帝汶', 'Timor Wschodni', 'Kelet-Timor', 'טימור לסטה'),
(227, 'TG', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Togo', 'Τόγκο', 'トーゴ', 'Togo', 'Togo', 'Того', '多哥', 'Togo', 'Togo', 'טוגו'),
(228, 'TK', 'Tokelau', 'Tokelau', 'Tokelau', 'Tokélaou', 'Tokelau', 'Tokelau', 'Tokelau', 'Τοκελάου', 'トケラウ', 'Tokelau', 'Tokelau', 'Токелау', '托克劳', 'Tokelau', 'Tokelau', 'טוקלאו'),
(229, 'TO', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Tonga', 'Τόνγκα', 'トンガ', 'Tonga', 'Tonga', 'Тонга', '汤加', 'Tonga', 'Tonga', 'טונגה'),
(230, 'TT', 'Trinidad & Toba', 'Trinidad e Toba', 'Trinidad und To', 'Trinité-et-Toba', 'Trinidad y Toba', 'Trinidad e Tobago', 'Trinidad și Tobago', 'Τρινιντάντ και Τομπά', 'トリニダード・トバゴ', 'Trinidad ha Tobago', 'Trinidad ja Tobago', 'Тринидад и Тобаго', '特立尼达和多巴哥', 'Trynidad i Tobago', 'Trinidad és Tobago', 'טרינידד וטובגו'),
(231, 'TA', 'Tristan da Cunh', 'Tristan da Cunh', 'Tristan da Cunh', 'Tristan da Cunh', 'Tristán de Acuñ', 'Tristão da Cunha', 'Tristan da Cunha', 'Τριστάν ντα Κούνια', 'トリスタン・ダ・クーニャ', 'Tristan da Cunha', 'Tristan da Cunha', 'Тристан-да-Кунья', '特里斯坦-达库尼亚群岛', 'Tristan da Cunha', 'Tristan da Cunha', 'טריסטן דה קונה'),
(232, 'TN', 'Tunisia', 'Tunisia', 'Tunesien', 'Tunisie', 'Túnez', 'Tunísia', 'Tunisia', 'Τυνησία', 'チュニジア', 'Tunizia', 'Tunisia', 'Тунис', '突尼斯', 'Tunezja', 'Tunézia', 'טוניסיה'),
(233, 'TR', 'Turkey', 'Turchia', 'Türkei', 'Turquie', 'Turquía', 'Turquia', 'Turcia', 'Τουρκία', 'トルコ', 'Turkia', 'Turkki', 'Турция', '土耳其', 'Turcja', 'Törökország', 'טורקיה'),
(234, 'TM', 'Turkmenistan', 'Turkmenistan', 'Turkmenistan', 'Turkménistan', 'Turkmenistán', 'Turcomenistão', 'Turkmenistan', 'Τουρκμενιστάν', 'トルクメニスタン', 'Turkmenistan', 'Turkmenistan', 'Туркменистан', '土库曼斯坦', 'Turkmenistan', 'Türkmenisztán', 'טורקמניסטן');
INSERT INTO `countries` (`id`, `iso_code`, `en_label`, `it_label`, `de_label`, `fr_label`, `es_label`, `pt_label`, `ro_label`, `el_label`, `jp_label`, `br_label`, `fi_label`, `ru_label`, `zh_label`, `pl_label`, `hu_label`, `he_label`) VALUES
(235, 'TC', 'Turks & Caicos ', 'Isole Turks e C', 'Turks- und Caic', 'Îles Turques-et', 'Islas Turcas y ', 'Ilhas Turks e Caicos', 'Insulele Turks și Ca', 'Νήσοι Τερκ και Κάικο', 'タークス・カイコス諸島', 'Inizi Turks ha Caico', 'Turks- ja Caicossaar', 'о-ва Тёркс и Кайкос', '特克斯和凯科斯群岛', 'Turks i Caicos', 'Turks- és Caicos-szi', 'איי טורקס וקאיקוס'),
(236, 'TV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Τουβαλού', 'ツバル', 'Tuvalu', 'Tuvalu', 'Тувалу', '图瓦卢', 'Tuvalu', 'Tuvalu', 'טובאלו'),
(237, 'UM', 'U.S. Outlying I', 'Altre isole ame', 'Amerikanische Ü', 'Îles mineures é', 'Islas menores a', 'Ilhas Menores Distan', 'Insulele Îndepărtate', 'Απομακρυσμένες Νησίδ', '合衆国領有小離島', 'Inizi diabell ar Sta', 'Yhdysvaltain erillis', 'Внешние малые о-ва (', '美国本土外小岛屿', 'Dalekie Wyspy Mniejs', 'Az Amerikai Egyesült', 'האיים המרוחקים הקטני'),
(238, 'VI', 'U.S. Virgin Isl', 'Isole Vergini A', 'Amerikanische J', 'Îles Vierges de', 'Islas Vírgenes ', 'Ilhas Virgens dos EU', 'Insulele Virgine Ame', 'Αμερικανικές Παρθένο', '米領ヴァージン諸島', 'Inizi Gwercʼh ar Sta', 'Yhdysvaltain Neitsyt', 'Виргинские о-ва (США', '美属维尔京群岛', 'Wyspy Dziewicze Stan', 'Amerikai Virgin-szig', 'איי הבתולה של ארצות '),
(239, 'UG', 'Uganda', 'Uganda', 'Uganda', 'Ouganda', 'Uganda', 'Uganda', 'Uganda', 'Ουγκάντα', 'ウガンダ', 'Ouganda', 'Uganda', 'Уганда', '乌干达', 'Uganda', 'Uganda', 'אוגנדה'),
(240, 'UA', 'Ukraine', 'Ucraina', 'Ukraine', 'Ukraine', 'Ucrania', 'Ucrânia', 'Ucraina', 'Ουκρανία', 'ウクライナ', 'Ukraina', 'Ukraina', 'Украина', '乌克兰', 'Ukraina', 'Ukrajna', 'אוקראינה'),
(241, 'AE', 'United Arab Emi', 'Emirati Arabi U', 'Vereinigte Arab', 'Émirats arabes ', 'Emiratos Árabes', 'Emirados Árabes Unid', 'Emiratele Arabe Unit', 'Ηνωμένα Αραβικά Εμιρ', 'アラブ首長国連邦', 'Emirelezhioù Arab Un', 'Arabiemiirikunnat', 'ОАЭ', '阿拉伯联合酋长国', 'Zjednoczone Emiraty ', 'Egyesült Arab Emírsé', 'איחוד האמירויות הערב'),
(242, 'GB', 'United Kingdom', 'Regno Unito', 'Vereinigtes Kön', 'Royaume-Uni', 'Reino Unido', 'Reino Unido', 'Regatul Unit', 'Ηνωμένο Βασίλειο', 'イギリス', 'Rouantelezh-Unanet', 'Iso-Britannia', 'Великобритания', '英国', 'Wielka Brytania', 'Egyesült Királyság', 'הממלכה המאוחדת'),
(243, 'UN', 'United Nations', 'nazioni unite', 'Vereinte Nation', 'Nations Unies', 'United Nations', 'Nações Unidas', 'Națiunile Unite', 'Ηνωμένα Έθνη', 'こくさいれんごう', 'United Nations', 'Yhdistyneet kansakun', 'Организация Объедине', '联合国', 'Organizacja Narodów ', 'ENSZ', 'האומות המאוחדות'),
(244, 'US', 'United States', 'Stati Uniti', 'Vereinigte Staa', 'États-Unis', 'Estados Unidos', 'Estados Unidos', 'Statele Unite ale Am', 'Ηνωμένες Πολιτείες', 'アメリカ合衆国', 'Stadoù-Unanet', 'Yhdysvallat', 'Соединенные Штаты', '美国', 'Stany Zjednoczone', 'Egyesült Államok', 'ארצות הברית'),
(245, 'UY', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguay', 'Uruguai', 'Uruguay', 'Ουρουγουάη', 'ウルグアイ', 'Uruguay', 'Uruguay', 'Уругвай', '乌拉圭', 'Urugwaj', 'Uruguay', 'אורוגוואי'),
(246, 'UZ', 'Uzbekistan', 'Uzbekistan', 'Usbekistan', 'Ouzbékistan', 'Uzbekistán', 'Uzbequistão', 'Uzbekistan', 'Ουζμπεκιστάν', 'ウズベキスタン', 'Ouzbekistan', 'Uzbekistan', 'Узбекистан', '乌兹别克斯坦', 'Uzbekistan', 'Üzbegisztán', 'אוזבקיסטן'),
(247, 'VU', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Βανουάτου', 'バヌアツ', 'Vanuatu', 'Vanuatu', 'Вануату', '瓦努阿图', 'Vanuatu', 'Vanuatu', 'ונואטו'),
(248, 'VA', 'Vatican City', 'Citt', 'Vatikanstadt', 'État de la Cité', 'Ciudad del Vati', 'Cidade do Vaticano', 'Statul Cetății Vatic', 'Βατικανό', 'バチカン市国', 'Vatikan', 'Vatikaani', 'Ватикан', '梵蒂冈', 'Watykan', 'Vatikán', 'הוותיקן'),
(249, 'VE', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Venezuela', 'Βενεζουέλα', 'ベネズエラ', 'Venezuela', 'Venezuela', 'Венесуэла', '委内瑞拉', 'Wenezuela', 'Venezuela', 'ונצואלה'),
(250, 'VN', 'Vietnam', 'Vietnam', 'Vietnam', 'Vietnam', 'Vietnam', 'Vietnã', 'Vietnam', 'Βιετνάμ', 'ベトナム', 'Viêt Nam', 'Vietnam', 'Вьетнам', '越南', 'Wietnam', 'Vietnam', 'וייטנאם'),
(251, 'WF', 'Wallis & Futuna', 'Wallis e Futuna', 'Wallis und Futu', 'Wallis-et-Futun', 'Wallis y Futuna', 'Wallis e Futuna', 'Wallis și Futuna', 'Ουάλις και Φουτούνα', 'ウォリス・フツナ', 'Wallis ha Futuna', 'Wallis ja Futuna', 'Уоллис и Футуна', '瓦利斯和富图纳', 'Wallis i Futuna', 'Wallis és Futuna', 'איי ווליס ופוטונה'),
(252, 'EH', 'Western Sahara', 'Sahara occident', 'Westsahara', 'Sahara occident', 'Sáhara Occident', 'Saara Ocidental', 'Sahara Occidentală', 'Δυτική Σαχάρα', '西サハラ', 'Sahara ar Cʼhornôg', 'Länsi-Sahara', 'Западная Сахара', '西撒哈拉', 'Sahara Zachodnia', 'Nyugat-Szahara', 'סהרה המערבית'),
(253, 'YE', 'Yemen', 'Yemen', 'Jemen', 'Yémen', 'Yemen', 'Iêmen', 'Yemen', 'Υεμένη', 'イエメン', 'Yemen', 'Jemen', 'Йемен', '也门', 'Jemen', 'Jemen', 'תימן'),
(254, 'ZM', 'Zambia', 'Zambia', 'Sambia', 'Zambie', 'Zambia', 'Zâmbia', 'Zambia', 'Ζάμπια', 'ザンビア', 'Zambia', 'Sambia', 'Замбия', '赞比亚', 'Zambia', 'Zambia', 'זמביה'),
(255, 'ZW', 'Zimbabwe', 'Zimbabwe', 'Simbabwe', 'Zimbabwe', 'Zimbabue', 'Zimbábue', 'Zimbabwe', 'Ζιμπάμπουε', 'ジンバブエ', 'Zimbabwe', 'Zimbabwe', 'Зимбабве', '津巴布韦', 'Zimbabwe', 'Zimbabwe', 'זימבבואה');


--
-- Indexes for table `countries`
--
ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT for table `countries`
--
ALTER TABLE `countries`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=256;COMMIT;

